title: Marcus Eilertsen # your name (or website title) here
logo: "/images/profile_photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Analyst | Python | R | SQL
  <br><br>
  Edinburgh, Scotland
  <br><br>
  <a href="https://www.linkedin.com/in/marcus-eilertsen/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
